### ISSUE TITLE
A few bash examples where it failed

### ISSUE THREAD

**Issue by Zerogiven** [bemeurer/beautysh#1]
Hi,

First, thanks for making this cause for my server stuff i write a lot of bash scripts so it's very useful for me.

But i have some examples for you where it failed :) I'm not very familiar with phyton but, i'm a developer long time, so if i'm finding some time i maybe debug it too, but i think maybe will be much faster than me solving this issues :)

It doesn't fail at any bash script, but 3 from 7 files i've tested

I've attached them, if you don't want open the zip you can get them here too:
https://github.com/ShrimpDev/BashUpdateChecker/blob/master/checker.sh
https://github.com/ShrimpDev/BashUpdateChecker/blob/master/checker/joomla3.sh
https://github.com/ShrimpDev/BashUpdateChecker/blob/master/checker/roundcube.sh

And here are the error messages:

From joomla3.sh and roundcube.sh: _File ./checker/roundcube.sh: error: indent/outdent mismatch: 1._

From checker.sh:
`Traceback (most recent call last):
  File "/usr/local/bin/beautysh", line 9, in <module>
    load_entry_point('beautysh==2.2.2', 'console_scripts', 'beautysh')()
  File "build/bdist.linux-armv7l/egg/beautysh/beautysh.py", line 10, in main
  File "build/bdist.linux-armv7l/egg/beautysh/beautysh.py", line 162, in main
  File "build/bdist.linux-armv7l/egg/beautysh/beautysh.py", line 146, in beautify_file
  File "build/bdist.linux-armv7l/egg/beautysh/beautysh.py", line 67, in beautify_string
  File "/usr/lib/python2.7/re.py", line 146, in search
    return _compile(pattern, flags).search(string)
  File "/usr/lib/python2.7/re.py", line 251, in _compile
    raise error, v # invalid expression
sre_constants.error: nothing to repeat`

[PartsOfMyBashUpdateChecker.zip](https://github.com/bemeurer/beautysh/files/189075/PartsOfMyBashUpdateChecker.zip)

**Comment by bemeurer** [comment]
Hey @Zerogiven, thanks a lot for the bug report, I appreciate it! As it stands I'm cramped with work, and can't really fix this at this time, but I'll see if I can find someone who can (if you know any Python coders who'd be interested to help out it'd be a blessing). Sorry I can't start working on this right away!

**Comment by bemeurer** [comment]
I can confirm this is now fixed.
