### ISSUE TITLE
Error: sre_constants.error: nothing to repeat at position 25

### ISSUE THREAD

**Issue by Jackymancs4** [bemeurer/beautysh#25]
Hello @bemeurer 

I encounter this error

```
Traceback (most recent call last):
  File "/usr/local/bin/beautysh", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/beautysh/beautysh.py", line 11, in main
    Beautify().main()
  File "/usr/local/lib/python3.6/site-packages/beautysh/beautysh.py", line 215, in main
    error |= self.beautify_file(path)
  File "/usr/local/lib/python3.6/site-packages/beautysh/beautysh.py", line 181, in beautify_file
    result, error = self.beautify_string(data, path)
  File "/usr/local/lib/python3.6/site-packages/beautysh/beautysh.py", line 76, in beautify_string
    if(re.search(here_string, test_record) and not
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/re.py", line 182, in search
    return _compile(pattern, flags).search(string)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/re.py", line 301, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/sre_compile.py", line 562, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/sre_parse.py", line 855, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/sre_parse.py", line 416, in _parse_sub
    not nested and not items))
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/sre_parse.py", line 616, in _parse
    source.tell() - here + len(this))
sre_constants.error: nothing to repeat at position 25
```

when trying to beautify this bash script

```bash
# Syntax-highlight JSON strings or files
# Usage: `json '{"foo":42}'` or `echo '{"foo":42}' | json`
function json() {
	if [ -t 0 ]; then # argument
		python -mjson.tool <<< "$*"
	else # pipe
		python -mjson.tool
	fi;
}
```

To test that the script actually works:
```bash
json '{"foo":42}'
echo '{"foo":42}' | json
```

I'm using beautysh 3.8

**Comment by bemeurer** [comment]
Fixed!
