### ISSUE TITLE
Error: when install with pip, it shows UnicodeDecodeError: 'cp950' codec can't decode...

### ISSUE THREAD

**Issue by perfectcream** [bemeurer/beautysh#44]
When I update beautysh, I got the following output...

```
c:\>pip` install -U beautysh
Collecting beautysh
  Using cached https://files.pythonhosted.org/packages/a9/2c/91a68193e758db22a92e08cb9f49898d545036aa20fee8db63a062c1449e/beautysh-3.12.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\fish\AppData\Local\Temp\pip-install-87geoahp\beautysh\setup.py", line 13, in <module>
        DESCRIPTION = fh.read()
    UnicodeDecodeError: 'cp950' codec can't decode byte 0xe2 in position 288: illegal multibyte sequence

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\fish\AppData\Local\Temp\pip-install-87geoahp\beautysh\

```

How to fix it?

In setup.py, please modify it as following...

```
--- with open("README.md", "r") as fh:
+++ with open("README.md", "r", encoding='utf8') as fh:
```

**Comment by bemeurer** [comment]
Fixed in release 4.0
